include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_use_of_visible_for_testing_member: error
    missing_required_param: error

linter:
  rules:
    # Code style
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    unnecessary_this: true
    avoid_unnecessary_containers: true

    # Safety & cleanliness
    avoid_print: true
    prefer_final_locals: true
    prefer_final_fields: true
    always_declare_return_types: true

    # Flutter specific
    use_key_in_widget_constructors: true
